config/routes.rb
Rails.application.routes.draw do
  resources :exchange_rates, only: :index

  namespace :charts do
    get 'historic-rates'
  end

  root 'exchange_rates#index'
end

app/models/application_record.rb
# Default class which models will inherit from in the app.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# Default class which all controllers will inherit from in the app.
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
# Controller for managing the data passed to the historic rates chart.
class ChartsController < ApplicationController
  def historic_rates
    @series_data = RateGetterService.get_rates(requested_currencies)
    render json: @series_data.chart_json
  end

  private

  def requested_currencies
    return 'EUR,USD,AUD' if session[:currency].blank?

    session[:currency]
  end
end

app/controllers/exchange_rates_controller.rb
# Controller for rendering main application page and requests from there.
class ExchangeRatesController < ApplicationController
  after_action :set_currency_cookie, only: :index

  def index; end

  private

  def set_currency_cookie
    session[:currency] = params[:currency]
  end
end

app/helpers/application_helper.rb
# Default Helper class which all others will inherit from in the app.
module ApplicationHelper
end

app/views/exchange_rates/_form.html.erb
<form>
  <%= button_tag 'EUR', name: 'currency', value: 'EUR', class: "btn euro" %>
  <%= button_tag 'USD', name: 'currency', value: 'USD', class: "btn usd" %>
  <%= button_tag 'AUD', name: 'currency', value: 'AUD', class: "btn aud" %>
  <%= button_tag 'Reset', name: nil, class: "btn reset" %>
</form>

app/views/exchange_rates/_line_chart.html.erb
<%= line_chart charts_historic_rates_path,
    id: 'historic-exchange-rates-chart',
    title: 'Historic Exchange Rates',
    prefix: 'R$',
    decimal: ',',
    legend: 'bottom',
    messages: {empty: 'No data'},
    points: false %>

app/views/exchange_rates/index.html.erb
<%= render 'line_chart' %>

<div style="padding-left: 50px">
  <p>
    <h3>Currencies</h3>
    <small>Select a single currency to track.</small>
  </p>
  <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HistoricExchangeRates</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>